sudo: required
services:
  - docker

before_install:
  - docker build -t masashiu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  masashiu/docker-react npm run test

# deploy:
#   # edge: true  # if missing bucket_name error
#   provider: elasticbeanstalk
#   region: "ap-northeast-1"
#   app: "uemura-docker"
#   env: "uemura-docker-env"
#   bucket_name: elasticbeanstalk-ap-northeast-1-085107194442
#   bucket_path: "uemura-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_KEY: $AWS_SECRET_KEY
